# Generated by Django 6.0.7 on 2026-07-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_attendance_department", "0001_initial"),
        ("plugin_rbac", "0006_adminplugin_deactivated_at_and_more"),
        (
            "saas_core_admin",
            "0003_subscription_currency_subscription_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="department",
        ),
        migrations.AddField(
            model_name="department",
            name="associated_plugin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="plugin_rbac.plugin",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="department_type",
            field=models.CharField(default="CLINICAL", max_length=20),
        ),
        migrations.AddField(
            model_name="doctor",
            name="staff_type",
            field=models.CharField(default="DR", max_length=3),
        ),
        migrations.AddField(
            model_name="nurse",
            name="staff_type",
            field=models.CharField(default="NS", max_length=3),
        ),
        migrations.AddField(
            model_name="receptionist",
            name="staff_type",
            field=models.CharField(default="RS", max_length=3),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("associated_plugin__isnull", False)),
                fields=("hospital", "associated_plugin"),
                name="unique_plugin_department_per_hospital",
            ),
        ),
    ]
