# Generated by Django 6.0.7 on 2026-07-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hr_attendance_department",
            "0002_remove_ward_department_department_associated_plugin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr_attendance_department.department",
            ),
        ),
    ]
