# Generated by Django 6.0.7 on 2026-07-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_attendance_department", "0003_ward_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr_attendance_department.department",
            ),
        ),
    ]
