# Generated by Django 6.0.7 on 2026-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_attendance_department", "0004_alter_ward_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(default="DP", max_length=20),
        ),
    ]
