# Generated by Django 6.0.7 on 2026-07-10 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr_attendance_department", "__first__"),
        ("saas_core_admin", "__first__"),
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("plan_type", models.CharField(default="Retail", max_length=50)),
                ("is_routed_via_tpa", models.BooleanField(default=False)),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "relationship_to_subscriber",
                    models.CharField(default="Self", max_length=50),
                ),
                (
                    "subscriber_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "subscriber_govt_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("clinical_notes", models.TextField(blank=True, null=True)),
                ("necessity_justification", models.TextField(blank=True, null=True)),
                (
                    "patient_identity_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("discharge_type", models.CharField(default="Routine", max_length=50)),
                ("is_mlc", models.BooleanField(default=False)),
                ("is_maternity", models.BooleanField(default=False)),
                (
                    "nhcx_claim_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("clinical_status", models.CharField(default="Draft", max_length=50)),
                (
                    "adminal_status",
                    models.CharField(default="Pending Bill", max_length=50),
                ),
                (
                    "claim_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("auditor_query_note", models.TextField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "total_cgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_sgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("invoice_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_billed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("clinical_payload", models.JSONField(blank=True, null=True)),
                ("admin_payload", models.JSONField(blank=True, null=True)),
                ("lifecycle_timeline", models.JSONField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.userappointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr_attendance_department.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas_core_admin.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(default="Retail", max_length=50)),
                (
                    "nhcx_routing_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TpaProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimMaternityDetail",
            fields=[
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="claim.claim",
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_type", models.CharField(default="Normal", max_length=50)),
                ("living_children", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClaimMlcDetail",
            fields=[
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="claim.claim",
                    ),
                ),
                ("fir_number", models.CharField(max_length=100)),
                ("police_station", models.CharField(max_length=150)),
                (
                    "cause_of_injury",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClaimDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("icd_code", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("priority", models.CharField(default="Medium", max_length=50)),
                (
                    "billing_diag_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("room_type", models.CharField(blank=True, max_length=50, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_by_role", models.CharField(max_length=3)),
                ("uploaded_by_id", models.BigIntegerField()),
                ("document_type", models.CharField(max_length=50)),
                ("document_mode", models.CharField(default="FILE", max_length=10)),
                ("file_url", models.TextField(blank=True, null=True)),
                ("file_size_kb", models.IntegerField(blank=True, null=True)),
                ("document_text", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimGovtPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("package_code", models.CharField(max_length=50)),
                ("package_name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mapped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimLabOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("loinc_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("sac_code", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("time_of_collection", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("drug_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("item_type", models.CharField(max_length=50)),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("procedure_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("priority", models.CharField(default="Routine", max_length=50)),
                (
                    "billing_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("sac_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claim.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="claim.insuranceprovider",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tpa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="claim.tpaprovider",
            ),
        ),
    ]
