# Generated by Django 6.0.7 on 2026-07-10 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"),
                    ("hh", "Bombay Phenotype (hh)"),
                    ("INRA", "INRA (Indian Rare)"),
                    ("OTHER", "Other Rare Type"),
                    ("UNKNOWN", "Unknown / Pending Test"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blood_group_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userblooddonation",
            name="blood_group",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("relation", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=15)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
