# Generated by Django 6.0.7 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas_core_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="npi_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
