# Generated by Django 6.0.7 on 2026-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas_core_admin", "0002_hospital_address_hospital_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price_annual",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
