# Generated by Django 6.0.7 on 2026-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_rbac", "0001_initial"),
        ("saas_core_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="permissionoverride",
            index=models.Index(
                fields=["staff_id", "staff_type"], name="plugin_rbac_staff_i_a909d6_idx"
            ),
        ),
    ]
