# Generated by Django 6.0.7 on 2026-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_rbac", "0002_permissionoverride_plugin_rbac_staff_i_a909d6_idx"),
        (
            "saas_core_admin",
            "0003_subscription_currency_subscription_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="permissionoverride",
            name="plugin_rbac_staff_i_a909d6_idx",
        ),
        migrations.AlterUniqueTogether(
            name="permissionoverride",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="adminplugin",
            name="active_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plugin",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="plugin",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plugin",
            name="price_annual",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="plugin",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="permissionoverride",
            name="staff_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="permissionoverride",
            index=models.Index(
                fields=["admin", "staff_type", "staff_id"],
                name="plugin_rbac_admin_i_a478a7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff_id__isnull", False)),
                fields=("admin", "staff_type", "staff_id", "permission"),
                name="unique_individual_permission_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff_id__isnull", True)),
                fields=("admin", "staff_type", "permission"),
                name="unique_role_permission_override",
            ),
        ),
    ]
