# Generated by Django 6.0.7 on 2026-07-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plugin_rbac",
            "0003_remove_permissionoverride_plugin_rbac_staff_i_a909d6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminplugin",
            name="active_status",
        ),
    ]
