# Generated by Django 6.0.7 on 2026-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_rbac", "0004_remove_adminplugin_active_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="tab_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
