# Generated by Django 6.0.7 on 2026-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_rbac", "0005_permission_tab_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminplugin",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plugin",
            name="is_unique_department",
            field=models.BooleanField(default=False),
        ),
    ]
