# Generated by Django 6.0.7 on 2026-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_rbac", "0006_adminplugin_deactivated_at_and_more"),
        (
            "saas_core_admin",
            "0003_subscription_currency_subscription_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permissionoverride",
            name="unique_individual_permission_override",
        ),
        migrations.RemoveConstraint(
            model_name="permissionoverride",
            name="unique_role_permission_override",
        ),
        migrations.RemoveIndex(
            model_name="permissionoverride",
            name="plugin_rbac_admin_i_a478a7_idx",
        ),
        migrations.RenameField(
            model_name="permissionoverride",
            old_name="staff_id",
            new_name="role_id",
        ),
        migrations.RenameField(
            model_name="permissionoverride",
            old_name="staff_type",
            new_name="role_type",
        ),
        migrations.AddField(
            model_name="permission",
            name="is_override",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="permissionoverride",
            index=models.Index(
                fields=["admin", "role_type", "role_id"],
                name="plugin_rbac_admin_i_80b9a3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role_id__isnull", False)),
                fields=("admin", "role_type", "role_id", "permission"),
                name="unique_individual_permission_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role_id__isnull", True)),
                fields=("admin", "role_type", "permission"),
                name="unique_role_permission_override",
            ),
        ),
    ]
