# Generated by Django 6.0.7 on 2026-07-10 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saas_core_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNetwork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cidr_block", models.CharField(max_length=50)),
                (
                    "network_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas_core_admin.admin",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiometricDeviceMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("device_ip", models.CharField(max_length=50)),
                ("punch_id", models.IntegerField()),
                ("staff_role", models.CharField(max_length=3)),
                ("staff_id", models.BigIntegerField()),
                ("is_currently_assigned", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_currently_assigned", True)),
                        fields=("device_ip", "punch_id"),
                        name="idx_unique_active_punch",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HospitalNetwork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cidr_block", models.CharField(max_length=50)),
                (
                    "network_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas_core_admin.hospital",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
